export const agents = [
  {
    name: "Michael Torres",
    title: "Senior Agent",
    location: "Manhattan, NY",
    deals: 312,
    rating: 4.9,
    specialty: "Luxury Residential",
    image: "/images/photo-1507003211169-0a1dd7228f2d-fad214d4fd80.jpg",
    badge: "Top Producer",
    phone: "+1 (212) 555-0142",
    email: "michael.torres@orbito.com",
    bio: "With over 12 years guiding clients through Manhattan's luxury market, Michael blends data-driven negotiation with old-school relationship building.",
    years: 12,
    languages: ["English", "Spanish"],
  },
  {
    name: "Shirin Khoury",
    title: "Luxury Specialist",
    location: "Brooklyn, NY",
    deals: 194,
    rating: 4.8,
    specialty: "High-End Condos",
    image: "/images/photo-1580489944761-15a19d654956-e3944a53e153.jpg",
    badge: "Award Winner",
    phone: "+1 (212) 555-0193",
    email: "shirin.khoury@orbito.com",
    bio: "Shirin specializes in Brooklyn's evolving condo landscape, pairing creative marketing with sharp pricing strategy.",
    years: 9,
    languages: ["English", "Arabic", "French"],
  },
  {
    name: "Mathew Reyes",
    title: "Buyer's Agent",
    location: "Queens, NY",
    deals: 228,
    rating: 5.0,
    specialty: "First-Time Buyers",
    image: "/images/photo-1472099645785-5658abf4ff4e-712d582e0514.jpg",
    badge: "5-Star Rated",
    phone: "+1 (212) 555-0118",
    email: "mathew.reyes@orbito.com",
    bio: "Mathew has guided hundreds of first-time buyers through every step of the process - from pre-approval to closing day.",
    years: 8,
    languages: ["English", "Spanish"],
  },
  {
    name: "Alicia Chen",
    title: "Investment Advisor",
    location: "Tribeca, NY",
    deals: 156,
    rating: 4.9,
    specialty: "Commercial & Multi-Family",
    image: "/images/photo-1438761681033-6461ffad8d80-387ee9cd98b7.jpg",
    badge: "Investment Pro",
    phone: "+1 (212) 555-0177",
    email: "alicia.chen@orbito.com",
    bio: "Alicia advises investors on yield-driven acquisitions across NYC's commercial and multi-family segments.",
    years: 11,
    languages: ["English", "Mandarin"],
  },
  {
    name: "James Okafor",
    title: "Commercial Agent",
    location: "Midtown, NY",
    deals: 281,
    rating: 4.8,
    specialty: "Office & Retail Spaces",
    image: "/images/photo-1500648767791-00dcc994a43e-dbe0cb7b4d96.jpg",
    badge: "Top Producer",
    phone: "+1 (212) 555-0156",
    email: "james.okafor@orbito.com",
    bio: "James leads complex office and retail leasing negotiations for tenants and landlords across Midtown.",
    years: 14,
    languages: ["English", "Yoruba"],
  },
  {
    name: "Sofia Martínez",
    title: "Relocation Expert",
    location: "Philadelphia, PA",
    deals: 143,
    rating: 4.9,
    specialty: "Corporate Relocations",
    image: "/images/photo-1534528741775-53994a69daeb-d78ae855a53e.jpg",
    badge: "Relocation Pro",
    phone: "+1 (215) 555-0103",
    email: "sofia.martinez@orbito.com",
    bio: "Sofia partners with Fortune 500 HR teams to relocate executives and families with minimal friction.",
    years: 10,
    languages: ["English", "Spanish", "Portuguese"],
  },
  {
    name: "Daniel Park",
    title: "New Dev Specialist",
    location: "West Village, NY",
    deals: 97,
    rating: 4.7,
    specialty: "New Developments",
    image: "/images/photo-1519085360753-af0119f7cbe7-7a4bdd20b50a.jpg",
    badge: "Rising Star",
    phone: "+1 (212) 555-0164",
    email: "daniel.park@orbito.com",
    bio: "Daniel specializes in pre-construction units, helping buyers secure value in NYC's newest developments.",
    years: 5,
    languages: ["English", "Korean"],
  },
  {
    name: "Priya Nair",
    title: "Senior Agent",
    location: "Upper West Side",
    deals: 208,
    rating: 4.9,
    specialty: "Pre-War Co-ops",
    image: "/images/photo-1487412720507-e7ab37603c6f-18a5f2902d2f.jpg",
    badge: "Award Winner",
    phone: "+1 (212) 555-0181",
    email: "priya.nair@orbito.com",
    bio: "Priya is a board-package expert for pre-war co-op buyers and sellers across the Upper West Side.",
    years: 13,
    languages: ["English", "Hindi", "Tamil"],
  },
  {
    name: "Carlos Rivera",
    title: "Rental Specialist",
    location: "Astoria, NY",
    deals: 175,
    rating: 4.8,
    specialty: "Long-Term Rentals",
    image: "/images/photo-1506794778202-cad84cf45f1d-43e3ce300e8c.jpg",
    badge: "Rental Expert",
    phone: "+1 (212) 555-0129",
    email: "carlos.rivera@orbito.com",
    bio: "Carlos matches renters with no-fee long-term apartments across Queens and Brooklyn.",
    years: 7,
    languages: ["English", "Spanish"],
  },
  {
    name: "Zoe Brennan",
    title: "Buyer's Agent",
    location: "Park Slope, NY",
    deals: 132,
    rating: 4.8,
    specialty: "Family Homes",
    image: "/images/photo-1544005313-94ddf0286df2-6a2430fc48ff.jpg",
    badge: "Rising Star",
    phone: "+1 (212) 555-0148",
    email: "zoe.brennan@orbito.com",
    bio: "Zoe focuses on growing families finding their first long-term home in brownstone Brooklyn.",
    years: 6,
    languages: ["English"],
  },
  {
    name: "Tom Haddad",
    title: "Luxury Lister",
    location: "Upper East Side",
    deals: 261,
    rating: 4.9,
    specialty: "Ultra-Luxury Properties",
    image: "/images/photo-1560250097-0b93528c311a-1065b79295df.jpg",
    badge: "Top Producer",
    phone: "+1 (212) 555-0192",
    email: "tom.haddad@orbito.com",
    bio: "Tom represents trophy properties on the Upper East Side, with discretion and global reach.",
    years: 16,
    languages: ["English", "Arabic"],
  },
  {
    name: "Naomi Watts",
    title: "Senior Agent",
    location: "Hoboken, NJ",
    deals: 118,
    rating: 4.7,
    specialty: "Waterfront Properties",
    image: "/images/photo-1573496359142-b8d87734a5a2-53d3fed501c2.jpg",
    badge: "Waterfront Pro",
    phone: "+1 (201) 555-0136",
    email: "naomi.watts@orbito.com",
    bio: "Naomi knows the Hudson waterfront block-by-block, helping buyers find skyline views without the Manhattan tax bill.",
    years: 9,
    languages: ["English"],
  },
];

export const badgeColors = {
  "Top Producer": { bg: "#151717", text: "#F1F1F1" },
  "Award Winner": { bg: "#2a2a1a", text: "#e8d97a" },
  "5-Star Rated": { bg: "#1a2a1a", text: "#7ae89a" },
  "Investment Pro": { bg: "#1a1a2a", text: "#7aa0e8" },
  "Relocation Pro": { bg: "#2a1a1a", text: "#e87a7a" },
  "Rising Star": { bg: "#1e2028", text: "#a78bfa" },
  "Rental Expert": { bg: "#1a2222", text: "#7ae8d8" },
  "Waterfront Pro": { bg: "#1a2030", text: "#7ab8e8" },
};

export const agentSlug = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const findAgentBySlug = (slug) =>
  agents.find((a) => agentSlug(a.name) === slug);
